### ISSUE TITLE
`serde(skip_serializing_if=...)` is not annotated as optional (`?`) in TypeScript definition

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [specta-rs/specta#300]
```toml
[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
specta = { version = "2.0.0-rc.20", features = ["derive"]}
specta-typescript = { version = "0.0.7" }
```
```rust
fn is_false(b: &bool) -> bool { !*b }

#[derive(serde::Serialize, specta::Type)]
struct MyStruct {
    #[serde(skip_serializing_if = "is_false")]
    flag: bool,
}

fn main() {
    println!("{}", specta_typescript::export::<MyStruct>(&specta_typescript::Typescript::new()).unwrap());
    println!("{}", serde_json::to_string(&MyStruct { flag: false }).unwrap());
}
```

I'm getting this:
```
export type MyStruct = { flag: boolean }
{}
```

Expected:
```
export type MyStruct = { flag?: boolean }
{}
```
