### ISSUE TITLE
Can't derive type `Type`

### ISSUE THREAD

**Issue by krant** [specta-rs/specta#386]
It seems it conflicts somehow with `derive` implementation. 
Following code compiles if I rename `Type` to something else:
```rs
#[derive(specta::Type)]
pub enum Type {
    A,
}

fn main() {
    let types = specta::TypeCollection::default().register::<Type>();
    specta_typescript::Typescript::default()
        .export_to("./bindings.ts", &types)
        .unwrap();
}
```
but when it's `Type` it fails with:
```
error[E0782]: expected a type, found a trait
 --> src/main.rs:2:10
  |
2 | pub enum Type {
  |          ^^^^
```
(that's all for `main` branch version)

**Comment by krant** [comment]
Sorry, I should have attached Cargo.toml from the beginning. It is enabled:
```TOML
[dependencies]
specta = { git = "https://github.com/specta-rs/specta.git", rev = "ab7d924", features = [
    "derive",
] }
```
